from pydantic import BaseModel, Field


class Message(BaseModel):
    """A single message in a chat conversation.

    Attributes:
        role: The participant role — one of ``system``, ``user``, or
            ``assistant``.
        content: The text content of the message.
    """

    role: str = Field(..., pattern=r"^(system|user|assistant)$")
    content: str


class ChatRequest(BaseModel):
    """Incoming request for a chat completion.

    Attributes:
        messages: Ordered conversation history (at least one message).
        model: Optional LiteLLM model identifier. Falls back to the
            server default when omitted.
        temperature: Sampling temperature between 0.0 and 1.0.
        max_tokens: Maximum number of tokens to generate.
        stream: Whether to stream the response (not yet supported).
    """

    messages: list[Message] = Field(..., min_length=1)
    model: str | None = None
    temperature: float = Field(default=0.7, ge=0.0, le=1.0)
    max_tokens: int = Field(default=1024, ge=1, le=4096)
    stream: bool = False


class Choice(BaseModel):
    """A single completion choice returned by the model.

    Attributes:
        index: Zero-based index of this choice.
        message: The assistant message generated by the model.
        finish_reason: Why generation stopped (e.g. ``stop``, ``length``).
    """

    index: int
    message: Message
    finish_reason: str | None = None


class Usage(BaseModel):
    """Token usage statistics for a completion.

    Attributes:
        prompt_tokens: Tokens consumed by the input prompt.
        completion_tokens: Tokens produced in the completion.
        total_tokens: Sum of prompt and completion tokens.
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class ChatResponse(BaseModel):
    """Response returned after a chat completion.

    Attributes:
        id: Unique identifier for the completion.
        model: The model that served the request.
        choices: List of generated completion choices.
        usage: Token usage breakdown, if available.
    """

    id: str
    model: str
    choices: list[Choice]
    usage: Usage | None = None
